In [1]:
import pandas as pd
df=pd.read_csv('netflix_titles.csv')
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [3]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [7]:
df.isna().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [9]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [11]:
df["release_year"].max()

2021

In [24]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
x=df[['show_id','type', 'title', 'director', 'cast', 'country', 'date_added', 'rating', 'duration', 'listed_in', 'description']]
y=df['release_year']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=100)
print(x_train.head())
print(x_test.head())
print(y_train.head())

print(y_test.head())

     show_id     type                                              title  \
1614   s1615  TV Show                                            Gormiti
5779   s5780    Movie  Unchained: The Untold Story of Freestyle Motoc...
3763   s3764    Movie                                    Elisa & Marcela
8625   s8626    Movie                              Tremors 5:  Bloodline
3837   s3838  TV Show                                          Jailbirds

                        director  \
1614                         NaN
5779  Paul Taublieb, Jon Freeman
3763               Isabel Coixet
8625            Don Michael Paul
3837                         NaN

                                                   cast  \
1614  Dermot Arrigan, Jenny Beacraft, Stephanie Figu...
5779                                        Josh Brolin
3763  Natalia de Molina, Greta FernÃ¡ndez, Sara Casas...
8625  Michael Gross, Jamie Kennedy, Ernest Ndhlovu, ...
3837                                                NaN

                          country        date_added rating  duration  \
1614                 Spain, Italy  December 1, 2020   TV-Y  1 Season
5779                United States   October 1, 2016  TV-MA    92 min
3763                        Spain      June 7, 2019  TV-MA   119 min
8625  South Africa, United States   January 1, 2020  PG-13    99 min
3837                          NaN      May 10, 2019  TV-MA  1 Season

                                       listed_in  \
1614                                    Kids' TV
5779                Documentaries, Sports Movies
3763  Dramas, International Movies, LGBTQ Movies
8625   Comedies, Horror Movies, Sci-Fi & Fantasy
3837                      Docuseries, Reality TV

                                            description
1614  Four friends become guardians of the island Go...
5779  This adrenaline-rush documentary traces the ri...
3763  In 1901 Spain, Elisa SÃ¡nchez Loriga adopts a m...
8625  When he is hired to capture a deadly creature ...
3837  At the Sacramento County Jail, incarcerated wo...
     show_id     type                           title      director  \
3695   s3696  TV Show                Rabbids Invasion           NaN
7338   s7339  TV Show  Los 10 aÃ±os de Peter Capusotto           NaN
6939   s6940    Movie      Haunting on Fraternity Row  Brant Sersen
6626   s6627    Movie     Don't Be Afraid of the Dark    Troy Nixey
3092   s3093  TV Show  Kevin Hart: Donâ€™t F**k This Up           NaN

                                                   cast  \
3695         Damien Laquet, David Gasman, Barbara Scaff
7338                      Diego Capusotto, Ivana Acosta
6939  Jacob Artist, Jayson Blair, Shanley Caswell, C...
6626  Katie Holmes, Guy Pearce, Bailee Madison, Jack...
3092                                                NaN

                               country         date_added rating  duration  \
3695                            France       July 1, 2019  TV-Y7  1 Season
7338                               NaN      June 29, 2018  TV-MA  1 Season
6939                     United States      March 1, 2019  TV-MA    99 min
6626  United States, Australia, Mexico   November 2, 2019      R    99 min
3092                     United States  December 27, 2019  TV-MA  1 Season

                                              listed_in  \
3695                              Kids' TV, TV Comedies
7338  International TV Shows, Spanish-Language TV Sh...
6939                  Horror Movies, Independent Movies
6626                                      Horror Movies
3092                                         Docuseries

                                            description
3695  Giant, rambunctious rabbits have invaded and a...
7338  Fictional personality Peter Capusotto parodies...
6939  When a fraternity's last big luau serves up ho...
6626  Young Sally Hurst discovers she isn't alone in...
3092  Amid turmoil in his career and marriage, comed...
1614    2018
5779    2016
3763    2019
8625    2015
3837    2019
Name: release_year, dtype: int64
3695    2018
7338    2015
6939    2018
6626    2010
3092    2019
Name: release_year, dtype: int64

In [28]:
x=df[['show_id','type', 'title', 'director', 'cast', 'country', 'date_added', 'rating', 'duration', 'listed_in', 'description']]
y=df['release_year']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=100, shuffle=False)
print(x_train.tail(1000))
print(x_test.tail(1000))
print(y_train.tail(1000))

print(y_test.tail(1000))

     show_id   type                         title  \
6045   s6046  Movie     A Mission in an Old Movie
6046   s6047  Movie           A Most Violent Year
6047   s6048  Movie          A Murder in the Park
6048   s6049  Movie              A new Capitalism
6049   s6050  Movie        A Night at the Roxbury
...      ...    ...                           ...
7040   s7041  Movie        I Am Not Madame Bovary
7041   s7042  Movie                   I Am Sun Mu
7042   s7043  Movie                I Am Vengeance
7043   s7044  Movie                    I Am Wrath
7044   s7045  Movie  I Don't Know How She Does It

                                 director  \
6045                       Ahmad El-Badri
6046                         J.C. Chandor
6047  Christopher S. Rech, Brandon Kimber
6048                                  NaN
6049                     John Fortenberry
...                                   ...
7040                        Feng Xiaogang
7041                         Adam SjÃ¶berg
7042                          Ross Boyask
7043                        Chuck Russell
7044                      Douglas McGrath

                                                   cast  \
6045  Edward, Fifi Abdo, Lotfy Labib, Madeleine Mata...
6046  Oscar Isaac, Jessica Chastain, David Oyelowo, ...
6047                                                NaN
6048                                                NaN
6049  Will Ferrell, Chris Kattan, Dan Hedaya, Molly ...
...                                                 ...
7040  Fan Bingbing, Guo Tao, Da Peng, Zhang Jiayi, Y...
7041                                                NaN
7042  Stu Bennett, Anna Shaffer, Mark Griffin, Bryan...
7043  John Travolta, Christopher Meloni, Amanda Schu...
7044  Sarah Jessica Parker, Pierce Brosnan, Greg Kin...

                                  country          date_added rating duration  \
6045                                  NaN      April 25, 2019  TV-MA   98 min
6046  United Arab Emirates, United States       July 22, 2018      R  125 min
6047                        United States      April 28, 2017  PG-13   91 min
6048                               Brazil       June 12, 2018  TV-14   76 min
6049                        United States    December 1, 2019  PG-13   82 min
...                                   ...                 ...    ...      ...
7040                                China   September 2, 2017  TV-14  139 min
7041    China, South Korea, United States    February 1, 2017     NR   88 min
7042                       United Kingdom   December 22, 2018      R   93 min
7043                        United States  September 16, 2019      R   91 min
7044                        United States      March 23, 2019  PG-13   89 min

                                   listed_in  \
6045          Comedies, International Movies
6046                       Dramas, Thrillers
6047                           Documentaries
6048     Documentaries, International Movies
6049                   Comedies, Cult Movies
...                                      ...
7040  Comedies, Dramas, International Movies
7041     Documentaries, International Movies
7042                      Action & Adventure
7043              Action & Adventure, Dramas
7044                                Comedies

                                            description
6045  A young man struggles with his overbearing mot...
6046  Abel Morales tries to avoid corruption's easy ...
6047  This documentary excoriates a noted anti-death...
6048  Entrepreneurs worldwide explore alternatives t...
6049  After a run-in with Richard Grieco, dimwits Do...
...                                                 ...
7040  To qualify for an apartment reserved for singl...
7041  A North Korean propagandist who escaped to Seo...
7042  After learning that an ex-military friend and ...
7043  Hell-bent on avenging his wife's murder, Stanl...
7044  In this affable yuppie comedy, Kate Reddy is a...

[1000 rows x 11 columns]
     show_id     type                 title          director  \
7807   s7808    Movie                Q Ball  Michael Tolajian
7808   s7809  TV Show     QuÃ© pena tu serie               NaN
7809   s7810    Movie     Quantum of Solace      Marc Forster
7810   s7811  TV Show  Queen of No Marriage               NaN
7811   s7812    Movie   Queen of the Desert     Werner Herzog
...      ...      ...                   ...               ...
8802   s8803    Movie                Zodiac     David Fincher
8803   s8804  TV Show           Zombie Dumb               NaN
8804   s8805    Movie            Zombieland   Ruben Fleischer
8805   s8806    Movie                  Zoom      Peter Hewitt
8806   s8807    Movie                Zubaan       Mozez Singh

                                                   cast  \
7807                                                NaN
7808  Ariel Levy, Andrea Velasco, Lucy Cominetti, Ig...
7809  Daniel Craig, Olga Kurylenko, Mathieu Amalric,...
7810  Ethan Juan, Cheryl Yang, Harry Chang, Sylvia Y...
7811  Nicole Kidman, James Franco, Damian Lewis, Jay...
...                                                 ...
8802  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...
8803                                                NaN
8804  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...
8805  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...
8806  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...

                            country         date_added rating   duration  \
7807                  United States     March 11, 2020  TV-MA     96 min
7808                  United States   November 4, 2016  TV-MA   1 Season
7809  United Kingdom, United States    August 31, 2020  PG-13    106 min
7810                         Taiwan     August 1, 2016  TV-MA   1 Season
7811         United States, Morocco      April 6, 2019  PG-13    128 min
...                             ...                ...    ...        ...
8802                  United States  November 20, 2019      R    158 min
8803                            NaN       July 1, 2019  TV-Y7  2 Seasons
8804                  United States   November 1, 2019      R     88 min
8805                  United States   January 11, 2020     PG     88 min
8806                          India      March 2, 2019  TV-14    111 min

                                              listed_in  \
7807                       Documentaries, Sports Movies
7808  International TV Shows, Romantic TV Shows, Spa...
7809                                 Action & Adventure
7810  International TV Shows, Romantic TV Shows, TV ...
7811                                             Dramas
...                                                 ...
8802                     Cult Movies, Dramas, Thrillers
8803             Kids' TV, Korean TV Shows, TV Comedies
8804                            Comedies, Horror Movies
8805                 Children & Family Movies, Comedies
8806     Dramas, International Movies, Music & Musicals

                                            description
7807  At San Quentin State Prison, hardened convicts...
7808  Javier is happily in love with Sofia, so when ...
7809  Picking up an hour after the events of 2006's ...
7810  Sparks begin to fly when a successful 33-year-...
7811  Driven beyond the bounds of convention, advent...
...                                                 ...
8802  A political cartoonist, a crime reporter and a...
8803  While living alone in a spooky town, a young g...
8804  Looking to survive in a world taken over by zo...
8805  Dragged from civilian life, a former superhero...
8806  A scrappy but poor boy worms his way into a ty...

[1000 rows x 11 columns]
6045    2012
6046    2014
6047    2014
6048    2017
6049    1998
        ...
7040    2016
7041    2015
7042    2018
7043    2016
7044    2011
Name: release_year, Length: 1000, dtype: int64
7807    2019
7808    2015
7809    2008
7810    2009
7811    2015
        ...
8802    2007
8803    2018
8804    2009
8805    2006
8806    2015
Name: release_year, Length: 1000, dtype: int64